extern crate proc_macro;

use std::{env, path::PathBuf, sync::LazyLock};

use proc_macro::TokenStream;
use syn::{Data, Expr};

use crate::io::write_ts_file;

mod io;

/// Base directory of the project, determined by the `CARGO_MANIFEST_DIR` environment variable.
const BASE_DIR: LazyLock<PathBuf> = LazyLock::new(|| {
    PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("Missing CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
});

/// TODO: This path should be configurable via an environment variable or a macro argument. For now, it is hardcoded to src/types
const TYPE_DIR: LazyLock<PathBuf> = LazyLock::new(|| BASE_DIR.join("types"));

const MANIFEST_FILE_NAME: &str = ".ts-types-manifest";

const FILE_HEADER: &str = "/**\n * This file has been autogenerated by the `ts-types` Rust crate. Any Modifications are futile.\n */\n\n";

/// The `ts_type` attribute macro is designed to be applied to structs (and potentially enums in the future),
/// and it performs certain operations related to TypeScript type generation (or other uses).
///
/// ### Usage:
/// ```rust
/// use ts_types_macros::ts_type;
/// #[ts_type]
/// struct MyStruct {
///     field1: i32,
///     field2: String,
/// }
/// ```
#[proc_macro_attribute]
pub fn ts_type(args: TokenStream, item: TokenStream) -> TokenStream {
    let file_name = parse_output_file_name(args);

    let my_cloned_item = item.clone();
    let input = syn::parse_macro_input!(my_cloned_item as syn::DeriveInput);
    let struct_identifier = &input.ident;

    match &input.data {
        Data::Struct(syn::DataStruct { fields, .. }) => {
            let mut ts_fields = Vec::new();

            for field in fields {
                let identifier = field.ident.as_ref().unwrap().to_string();
                let ts_type = rust_type_to_ts_type(&field.ty);
                let ts_field = format!("\t{}: {};", identifier, ts_type);

                ts_fields.push(ts_field);
            }
            // Construct the full TypeScript type definition
            let final_file_name = file_name.unwrap_or_else(|| format!("{}.ts", struct_identifier));
            let ts_type_string = format!(
                "{}export type {} = {{\n{}\n}};\n",
                FILE_HEADER,
                struct_identifier,
                ts_fields.join("\n")
            );
            // Write the generated TypeScript to a .ts file
            write_ts_file(
                &final_file_name,
                &ts_type_string,
                &struct_identifier.to_string(),
            );
        }
        Data::Enum(_) => todo!("Implement Enum type gen"),
        _ => panic!("Unions not supported type"),
    }
    item
}

// Helper function to map Rust types to TypeScript types
fn rust_type_to_ts_type(ty: &syn::Type) -> String {
    match ty {
        syn::Type::Path(type_path) => {
            let segment = type_path.path.segments.last().unwrap();
            match segment.ident.to_string().as_str() {
                "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "f32" | "f64" => {
                    "number".to_string()
                }
                "String" => "string".to_string(),
                "bool" => "boolean".to_string(),
                "Vec" => {
                    if let syn::PathArguments::AngleBracketed(args) = &segment.arguments {
                        if let Some(syn::GenericArgument::Type(inner_ty)) = args.args.first() {
                            let ts_inner_type = rust_type_to_ts_type(inner_ty); // Recursively map inner type
                            return format!("Array<{}>", ts_inner_type);
                        }
                    }
                    return "any".to_string();
                }
                _x => "x".to_string(),
            }
        }
        _x => "x".to_string(), // Handle other cases, default to `any`
    }
}

fn parse_output_file_name(args: TokenStream) -> Option<String> {
    if args.is_empty() {
        return None;
    }

    let meta = syn::parse::<syn::Meta>(args).unwrap_or_else(|err| {
        panic!("Failed to parse macro arguments: {err}");
    });

    if !meta.path().is_ident("path") {
        return None;
    }

    match meta {
        syn::Meta::NameValue(meta_name) => match meta_name.value {
            Expr::Lit(expr_lit) => match expr_lit.lit {
                syn::Lit::Str(lit_str) => Some(lit_str.value()),
                _ => panic!("Expected a string literal for the path value."),
            },
            _ => panic!("Expected a literal expression for the path value."),
        },
        _ => panic!("Could not find Meta::List: {:?}", meta),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{
        fs,
        time::{SystemTime, UNIX_EPOCH},
    };

    fn temp_output_dir() -> PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
            .to_string();
        let dir = std::env::temp_dir().join(format!("ts-types-test-{unique}"));
        fs::create_dir_all(dir.join("dump")).unwrap();
        dir
    }

    #[test]
    fn changing_output_path_removes_the_old_generated_file() {
        let temp_dir = temp_output_dir();
        let original_dir = std::env::current_dir().unwrap();
        std::env::set_current_dir(&temp_dir).unwrap();

        write_ts_file("old.ts", "old", "Exercise");
        write_ts_file("new.ts", "new", "Exercise");

        assert!(!temp_dir.join("dump/old.ts").exists());
        assert!(temp_dir.join("dump/new.ts").exists());

        std::env::set_current_dir(original_dir).unwrap();
        let _ = fs::remove_dir_all(temp_dir);
    }
}
